wonik_robot_omni_wheel_front_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: wonik_robot_omni_wheel_front_left_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

wonik_robot_omni_wheel_front_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: wonik_robot_omni_wheel_front_right_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

wonik_robot_omni_wheel_back_left_controller:
    type: velocity_controllers/JointVelocityController
    joint: wonik_robot_omni_wheel_back_left_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

wonik_robot_omni_wheel_back_right_controller:
    type: velocity_controllers/JointVelocityController
    joint: wonik_robot_omni_wheel_back_right_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

# wheel_controller:
#   type: velocity_controllers/JointTrajectoryController
#   joints:
#      - wonik_robot_omni_wheel_front_left_joint
#      - wonik_robot_omni_wheel_front_right_joint
#      - wonik_robot_omni_wheel_back_left_joint
#      - wonik_robot_omni_wheel_back_right_joint
#   gains:
#     wonik_robot_omni_wheel_front_left_joint:  {p: 100,  d: 1, i: 1, i_clamp: 1}
#     wonik_robot_omni_wheel_front_right_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     wonik_robot_omni_wheel_back_left_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     wonik_robot_omni_wheel_back_right_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}