
footprint: [[0.55,0.45],[-0.55,0.45],[-0.55,-0.45],[0.55,-0.45]]

inflation_layer:
  inflation_radius: 1
  cost_scaling_factor: 5

observation_sources: lidar_1 lidar_2

lidar_1: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: /lidar_1/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}

lidar_2: {sensor_frame: lidar_2_link , data_type: LaserScan, topic: /lidar_2/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}

camera_1: {sensor_frame: cam_1_link , data_type: LaserScan, topic: /cam_1/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}



# footprint: [[0.5,0.4],[-0.5,0.4],[-0.5,-0.4],[0.5,-0.4]]

# inflation_layer:
#   inflation_radius: 1
#   cost_scaling_factor: 5

# observation_sources: lidar_1 lidar_2 camera_1 #camera_2
# lidar_1: {sensor_frame: lidar_1_link , data_type: LaserScan, topic: /lidar_1/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}
# lidar_2: {sensor_frame: lidar_2_link , data_type: LaserScan, topic: /lidar_2/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}
# camera_1: {sensor_frame: cam_1_link , data_type: LaserScan, topic: /cam_1/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}
# camera_2: {sensor_frame: cam_2_link , data_type: LaserScan, topic: /cam_2/scan, marking: true, clearing: true, obstacle_range: 5, raytrace_range: 8}
