################################################################
################################################################
#                                                              #
#          .yaml for Wonik Robot                               #
#                                                              #
################################################################
################################################################

use_MDUI: 0
wheel_radius: 0.0935 # not use
wheel_length: -0.454 # not use
motor_pole: 10
reduction: 30
reverse_direction: 0
maxrpm: 1000
motor_posi: 0
encoder_PPR: 16384
position_proportion_gain: 20
speed_proportion_gain: 50
integral_gain: 1800
slow_start: 300
slow_down: 300
port1: /dev/ttyUSB0
port2: /dev/ttyUSB1

joint_name1: wheel_front_left_joint
joint_name2: wheel_front_right_joint
joint_name3: wheel_rear_left_joint
joint_name4: wheel_rear_right_joint



#################################################
#              motor configuration              #
#################################################
drive1: # FL
  ip_address: 10.42.0.114
  port: 3002
  gear_ratio: 8
  joint_name: wheel_front_left_joint

drive2: # FR
  ip_address: 10.42.0.115
  port: 3002
  gear_ratio: 8
  joint_name: wheel_front_right_joint
  
drive3: # RL
  ip_address: 10.42.0.116
  port: 3002
  gear_ratio: 8
  joint_name: wheel_rear_left_joint

drive4: # RR
  ip_address: 10.42.0.117
  port: 3002
  gear_ratio: 8
  joint_name: wheel_rear_right_joint