#robot's geometric parameters:

# tuning factor
pacticalFactor: 1.15
#Diameter of std. mecanum wheel
wheelDiameter: 0.152
#Length of the mobile robot from wheel center to wheel center
robotLength: 0.6 # 0.600
#Width from wheel center to wheel center
robotWidth: 0.602 # 0.602
#stddev vel x
devX: 0.447
#stddev vel y
devY: 0.447
#stddev vel z
devZ: 0.447
#stddev vel roll
devRoll: 0.447
#stddev vel pitch
devPitch: 0.447
#stddev vel x yaw
devYaw: 0.447